DROP TABLE IF EXISTS "payment";
DROP TABLE IF EXISTS "qna";
DROP TABLE IF EXISTS "chat";
DROP TABLE IF EXISTS "menu";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "image";
DROP TABLE IF EXISTS "menu_category";
DROP TABLE IF EXISTS "room";
DROP TABLE IF EXISTS "store";
DROP TABLE IF EXISTS "user";

