DROP TABLE IF EXISTS "payment" CASCADE;
DROP TABLE IF EXISTS "qna" CASCADE;
DROP TABLE IF EXISTS "chat" CASCADE;
DROP TABLE IF EXISTS "menu" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS "image" CASCADE;
DROP TABLE IF EXISTS "menu_category" CASCADE;
DROP TABLE IF EXISTS "room" CASCADE;
DROP TABLE IF EXISTS "store" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

