-- USER TABLE
ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;
-- CHAT TABLE
ALTER TABLE "chat" DISABLE ROW LEVEL SECURITY;
-- PAYMENT TABLE
ALTER TABLE "payment" DISABLE ROW LEVEL SECURITY;
-- ROOM TABLE
ALTER TABLE "room" DISABLE ROW LEVEL SECURITY;
-- ROOM_JOIN TABLE
ALTER TABLE "room_join" DISABLE ROW LEVEL SECURITY;
-- ORDER TABLE
ALTER TABLE "order" DISABLE ROW LEVEL SECURITY;
-- MENU_CATEGORY TABLE
ALTER TABLE "menu_category" DISABLE ROW LEVEL SECURITY;
-- MENU TABLE
ALTER TABLE "menu" DISABLE ROW LEVEL SECURITY;
-- IMAGE TABLE
ALTER TABLE "image" DISABLE ROW LEVEL SECURITY;
-- STORE TABLE
ALTER TABLE "store" DISABLE ROW LEVEL SECURITY;
