CREATE TABLE "user"(
    "id" UUID NOT NULL,
    "nickname" TEXT NOT NULL,
    "user_rating" FLOAT(53) DEFAULT 50.0,
    "cash" BIGINT DEFAULT 0,
				"profile_url" TEXT,
				"address" TEXT,
				"room_address_detail" TEXT,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now()
);
ALTER TABLE
    "user" ADD PRIMARY KEY("id");
CREATE TABLE "room"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "store_id" BIGINT NOT NULL,
    "room_name" TEXT NOT NULL,
    "room_address" TEXT NOT NULL,
    "max_people" INTEGER NOT NULL,
    "users" jsonb default '[]'::jsonb,
    "leader_id" UUID NOT NULL,
    "status" TEXT DEFAULT '모집중', -- '모집중','진행중','마감'
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now()
);
ALTER TABLE
    "room" ADD PRIMARY KEY("id");
CREATE TABLE "room_join"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
				"room_id" BIGINT NOT NULL,
				"user_id" UUID,
				"joined_at" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now(),
				"status" TEXT DEFAULT '준비중' -- '준비중','준비완료'
);
ALTER TABLE
    "room_join" ADD PRIMARY KEY("id");
CREATE TABLE "store"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "category_id" TEXT NOT NULL,
    "store_name" TEXT NOT NULL,
    "store_address" TEXT NOT NULL,
    "min_price" BIGINT DEFAULT 10000,
    "tel" TEXT NOT NULL
);
ALTER TABLE
    "store" ADD PRIMARY KEY("id");
CREATE TABLE "menu_category"(
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL
);
ALTER TABLE
    "menu_category" ADD PRIMARY KEY("id");
CREATE TABLE "order"(
    "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "room_id" BIGINT NOT NULL,
    "user_id" UUID NOT NULL,
    "store_id" BIGINT NOT NULL,
    "room_order" jsonb NOT NULL,
    "total_price" BIGINT NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now()
);
ALTER TABLE
    "order" ADD PRIMARY KEY("order_id");
CREATE TABLE "menu"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "store_id" BIGINT NOT NULL,
    "img_id" BIGINT NOT NULL,
    "menu_name" TEXT NOT NULL,
    "menu_price" BIGINT NOT NULL
);
ALTER TABLE
    "menu" ADD PRIMARY KEY("id");
CREATE TABLE "chat"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "room_id" BIGINT NOT NULL,
    "chat" TEXT NOT NULL,
    "user_id" UUID NOT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now()
);
ALTER TABLE
    "chat" ADD PRIMARY KEY("id");
CREATE TABLE "image"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "bucket" TEXT NOT NULL,
    "folder" TEXT NOT NULL,
    "filename" TEXT NOT NULL
);
ALTER TABLE
    "image" ADD PRIMARY KEY("id");
CREATE TABLE "qna"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "q_contents" TEXT NOT NULL,
    "q_answer" TEXT NULL,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);
ALTER TABLE
    "qna" ADD PRIMARY KEY("id");
CREATE TABLE "payment"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "order_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "amount" BIGINT NOT NULL
);
ALTER TABLE
    "payment" ADD PRIMARY KEY("id");
-- order.user_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'order_user_id_foreign'
    ) THEN
        ALTER TABLE "order" DROP CONSTRAINT "order_user_id_foreign";
    END IF;
END$$;
ALTER TABLE "order"
    ADD CONSTRAINT "order_user_id_foreign"
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

-- chat.room_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chat_room_id_foreign'
    ) THEN
        ALTER TABLE "chat" DROP CONSTRAINT "chat_room_id_foreign";
    END IF;
END$$;
ALTER TABLE "chat"
    ADD CONSTRAINT "chat_room_id_foreign"
    FOREIGN KEY ("room_id") REFERENCES "room" ("id");

-- chat.user_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'chat_user_id_foreign'
    ) THEN
				    ALTER TABLE "chat" DROP CONSTRAINT "chat_user_id_foreign";
				END IF;
END$$;
ALTER TABLE "chat"
    ADD CONSTRAINT "chat_user_id_foreign"
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

-- room.leader_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'room_leader_id_foreign'
    ) THEN
        ALTER TABLE "room" DROP CONSTRAINT "room_leader_id_foreign";
    END IF;
END$$;
ALTER TABLE "room"
    ADD CONSTRAINT "room_leader_id_foreign"
    FOREIGN KEY ("leader_id") REFERENCES "user" ("id");

-- room_join.user_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'room_join_user_id_foreign'
				) THEN
				    ALTER TABLE "room_join" DROP CONSTRAINT "room_join_user_id_foreign";
				END IF;
END$$;
ALTER TABLE "room_join"
    ADD CONSTRAINT "room_join_user_id_foreign"
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

-- room_join.room_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'room_join_room_id_foreign'
				) THEN
				    ALTER TABLE "room_join" DROP CONSTRAINT "room_join_room_id_foreign";
				END IF;
END$$;
ALTER TABLE "room_join"
    ADD CONSTRAINT "room_join_room_id_foreign"
    FOREIGN KEY ("room_id") REFERENCES "room" ("id");

-- menu.img_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'menu_img_id_foreign'
    ) THEN
        ALTER TABLE "menu" DROP CONSTRAINT "menu_img_id_foreign";
    END IF;
END$$;
ALTER TABLE "menu"
    ADD CONSTRAINT "menu_img_id_foreign"
    FOREIGN KEY ("img_id") REFERENCES "image" ("id");

-- payment.user_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'payment_user_id_foreign'
    ) THEN
        ALTER TABLE "payment" DROP CONSTRAINT "payment_user_id_foreign";
    END IF;
END$$;
ALTER TABLE "payment"
    ADD CONSTRAINT "payment_user_id_foreign"
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

-- room.store_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'room_store_id_foreign'
    ) THEN
        ALTER TABLE "room" DROP CONSTRAINT "room_store_id_foreign";
    END IF;
END$$;
ALTER TABLE "room"
    ADD CONSTRAINT "room_store_id_foreign"
    FOREIGN KEY ("store_id") REFERENCES "store" ("id");

-- order.store_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'order_store_id_foreign'
    ) THEN
        ALTER TABLE "order" DROP CONSTRAINT "order_store_id_foreign";
    END IF;
END$$;
ALTER TABLE "order"
    ADD CONSTRAINT "order_store_id_foreign"
    FOREIGN KEY ("store_id") REFERENCES "store" ("id");

-- qna.user_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'qna_user_id_foreign'
    ) THEN
        ALTER TABLE "qna" DROP CONSTRAINT "qna_user_id_foreign";
    END IF;
END$$;
ALTER TABLE "qna"
    ADD CONSTRAINT "qna_user_id_foreign"
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

-- order.room_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'order_room_id_foreign'
    ) THEN
        ALTER TABLE "order" DROP CONSTRAINT "order_room_id_foreign";
    END IF;
END$$;
ALTER TABLE "order"
    ADD CONSTRAINT "order_room_id_foreign"
    FOREIGN KEY ("room_id") REFERENCES "room" ("id");

-- payment.order_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'payment_order_id_foreign'
    ) THEN
        ALTER TABLE "payment" DROP CONSTRAINT "payment_order_id_foreign";
    END IF;
END$$;
ALTER TABLE "payment"
    ADD CONSTRAINT "payment_order_id_foreign"
    FOREIGN KEY ("order_id") REFERENCES "order" ("order_id");

-- store.category_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'store_category_id_foreign'
    ) THEN
        ALTER TABLE "store" DROP CONSTRAINT "store_category_id_foreign";
    END IF;
END$$;
ALTER TABLE "store"
    ADD CONSTRAINT "store_category_id_foreign"
    FOREIGN KEY ("category_id") REFERENCES "menu_category" ("id");

-- menu.store_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'menu_store_id_foreign'
    ) THEN
        ALTER TABLE "menu" DROP CONSTRAINT "menu_store_id_foreign";
    END IF;
END$$;
ALTER TABLE "menu"
    ADD CONSTRAINT "menu_store_id_foreign"
    FOREIGN KEY ("store_id") REFERENCES "store" ("id");

